### ISSUE TITLE
Add pre-commit hook

### ISSUE THREAD

**Issue by nstarman** [ota-meshi/eslint-plugin-toml#215]
@ota-meshi, this tool looks super useful. It would be great if it could be used with pre-commit!

**Comment by ota-meshi** [comment]
I think you can do that just by configuring eslint using lint-staged or similar: 
https://github.com/lint-staged/lint-staged

**Comment by nstarman** [comment]
Thanks! I'm not familiar with that tooling ecosystem, but I'll give it a look.
