### ISSUE TITLE
config["flat/recommended"] and config["flat/standard"] rules have no file scope

### ISSUE THREAD

**Issue by ajslater** [ota-meshi/eslint-plugin-toml#234]
placing `...eslintPluginToml.configs["flat/base"],` in the top level of an eslint.config.js works well because the rules block in flat/base includes a file scope for `"**/*.toml"` files.

placing `...eslintPluginToml.configs["flat/standard"],` or `...eslintPluginToml.configs["flat/recommended"],` in the top level on enslint.config.js also expands "flat/base" rules which behave as expected, but since neither rht standard or recommended rules blocks include a file scope, eslint tries to to apply those toml rules to other kinds of files, like json or markdown. This crashes eslint because the source object doesn't have the properties that the toml rules expect because they weren't parsed as toml.

```
TypeError: Error while loading rule 'toml/no-unreadable-number-separator': Cannot read properties of undefined (reading 'defineCustomBlocksVisitor')
Occurred while linting /Users/aj/Code/codex/package.json
```

I suggest that that flat/standard and flat/recommended rules each include a files line like flat/base does:

```js
{
  files: ["*.toml", "**/*.toml"],
  rules: { 
    ... 
  }
},
``` 

**Workaround**
expand flat/base to do most of it. Then create a custom rules block that imports the extended ruleset with files scope. 
```js
...eslintPluginToml.configs["flat/base"],
{
  files: ["*.toml", "**/*.toml"],
  rules: {
    ...eslintPluginToml.configs["flat/recommended"].rules,
  },
},
```

**Comment by ajslater** [comment]
eslint-plugin-yml has the same issue, but I wanna see your thoughts on this before I open an identical issue over there.

**Comment by ota-meshi** [comment]
Thank you for posting this issue.
I think the problem is that this plugin is not compatible with language plugins other than `@eslint/js`.
Specifically, this plugin needs to be fixed so that it doesn't crash.
This plugin and plugin-yml are designed to work with `.vue` etc, so I don't want to configure it to enable rules by extension.

**Comment by ota-meshi** [comment]
By the way, how do other plugins such as typescript-eslint work around this problem? 🤔

**Comment by ota-meshi** [comment]
Hmm. I tried `@eslint/js` but those rules also crash on `json` languages.
I'm not sure what the best way to do that is 🤔 

[Online Demo](https://eslint-online-playground.netlify.app/#eNq1kzFvgzAQhf+K5TFKYMpCl0rt1KEdOtYZkH0gJ8a2bBMlQvz33hlEG0VVGdoFZN57d9+h88BjkCVc6s4bKI7R2T2v+CAsY4I3zglesWHc3p9HYfmWQzTapkI62+gW45jVnXchMSrFmuA6zD1OtpK+Cf4g7OK5d2RdWLhkh4Km7k1iHwRwjHOjWASQruvAKlDIIhICiySSN32rbUTE6SwStcwOkYh6fuK7LBl1ZC/vb6+s0Qbitzr5XGFXvtmUm/xbBD/MdUxt275uoUJuUuaxZjX0OboAzB7rdqr3Rss6we4EV5yT8hCCC0v2Z8KnNYgSC2HN4hylU7COmzL/Cb5fA77/BRL1P4U84Irh8vpanrBVRvha+nT1MMU7p7BdzpOg4PwMnnbOSo0j0U0ghbTbDaewQZSIfDlMlslxK5KGF2nk4yePEjvY)

**Comment by ajslater** [comment]
I guess my real question here is about consistency.

> This plugin and plugin-yml are designed to work with .vue etc, so I don't want to configure it to enable rules by extension.

The eslint-plugin-toml base configuration uses a files filter that already excludes the base configuration rules from anything but *.toml files.
The toml standard and recommended configurations apply their rules to every file and include the base configuration. Using the recommended configuration therefore only filters some rules by file extension and applies others to every file.

I think adding a files definition to the standard and recommended rulesets would alleviate this inconsistency.
An alternative would be to remove the files filter from the base configuration and specify in the documentation that the usage occur with user specified files blocks similar to the [@eslint/json documentation.](https://github.com/eslint/json/blob/main/README.md)

As it is, It's possible to use the toml plugin today alongside json & markdown files either by using the workaround I presented above which leverages your convenient base configuration or the user can rewrite the base configuration themselves to include the standard, recommended, or custom rules they like, but that removes much of the utility of preset configurations.

The typescript-eslint codebase is large but a cursory look indicates that including any of the typescript-eslint configurations replaces the current parser (likely js) with @typescript-eslint/parser. That parser comprehensively handles JS, TS,  JSON, JSX and TSX.  Whereas the @eslint/js parser does not handle json and crashes in a similar manner trying to apply js rules to it. However typescript-eslint/parser does not include parsers for other languages, so if for instance, *.md is included in a block that doesn't define an markdown parser, eslint will throw a parsing error. If using typescript-eslint with markdown linting I would have to segregate it into a `files: ["**/.js", "**/.ts"]` block.

You mentioned .vue compatibility, but I'm not aware of ways that toml or yaml would occur inside .vue files. Are there vue option blocks that might contain toml or yaml?

**Comment by ota-meshi** [comment]
If you want to use the recommended config only for your specific files, you can do so like this:

```js
import eslintPluginToml from 'eslint-plugin-toml';
export default [
  ...eslintPluginToml.configs['flat/recommended']
    .map(config=>({...config, files: ['path/to/*.toml']})),
}
```

The `<i18n>` block can use different languages ​​using the `lang` attribute.

https://github.com/intlify/bundle-tools/tree/main/packages/vite-plugin-vue-i18n#locale-messages-formatting

**Comment by ajslater** [comment]
That is more compact than what I'm doing, thanks.
